### ISSUE TITLE
Support for Multi-factor Authentication

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#418]
# Goals

- Allow users to register a second factor for their account
	- Supported second-factor type: 
		- TOTP app, e.g., Google Authenticator
		- Yubikey? (later)
- Allow applications to request that users authenticate using MFA
- Signal in IDTokens returned by IAM whether MFA was used during authentication

# Tasks
- [ ] Define changes to the database schema and persistence layer to store 2nd factor information linked to accounts
- [ ] Define the API used to register and manage second factors
- [ ] MFA support in auth flows
- [ ] Support for signaling that MFA is required for a given session by client apps (e.g.,  OpenID Connect's acr, but we should look also into what AARC/AEGIS is proposing on this)
- [ ] Support for signaling that MFA was used in an auth session (e.g.,  OpenID Connect's amr but we should look also into what AARC/AEGIS is proposing on this)
