### ISSUE TITLE
Nested groups

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#81]
Currently groups are flat in the IAM. 

Add support for enforcing a hierarchical structure over groups. This issue tracks development of 
the support for nested groups in the IAM SCIM APIs, while dashboard changes are tracked in #88.

## Subtasks

- [x] Changes to the database to have the hierarchical structure reflected in the IAM groups table
- [x] Changes to SCIM API to allow for creation of nested groups
- [x] Tests covering nested group creation and removal

### Changes to the database

The parent/child relationship can be easily created with a nullable one-to-many association among the parent and the children. Groups with a null parent are placed at the first level in the hierarchy.

### Changes to SCIM API to allow for creation/removal of nested groups

SCIM supports nested groups by allowing a group to be listed as a member of the parent group.
Our current implementation only supports members of type user. The implementation must be changed to support addition/removal of subgroups.

The addition of a subgroup is possible only at group creation time. We are not going to 
support "moving" groups in the hierarchical structure.

### Tests

Tests, implemented in MockMVC, check the correct behavior of nested group management operations.
